/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOpsProxyFactory,
  IOpsProxyFactoryInterface,
} from "../../../../contracts/offchain-helpers/AutomateReady.sol/IOpsProxyFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getProxyOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOpsProxyFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IOpsProxyFactoryInterface {
    return new Interface(_abi) as IOpsProxyFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOpsProxyFactory {
    return new Contract(address, _abi, runner) as unknown as IOpsProxyFactory;
  }
}
