/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AutomateReady } from "./AutomateReady";
export type { IAutomate } from "./IAutomate";
export type { IOpsProxyFactory } from "./IOpsProxyFactory";
export type { ITaskTreasuryUpgradable } from "./ITaskTreasuryUpgradable";
