/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  EuphratesMsgReceiverAppUpg,
  EuphratesMsgReceiverAppUpgInterface,
} from "../../../../contracts/LiquidityMining/CrossChainMsg/EuphratesMsgReceiverAppUpg";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "MsgNotFromReceiveEndpoint",
    type: "error",
  },
  {
    inputs: [],
    name: "euphratesMsgReceiveEndpoint",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "executeMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class EuphratesMsgReceiverAppUpg__factory {
  static readonly abi = _abi;
  static createInterface(): EuphratesMsgReceiverAppUpgInterface {
    return new Interface(_abi) as EuphratesMsgReceiverAppUpgInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EuphratesMsgReceiverAppUpg {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as EuphratesMsgReceiverAppUpg;
  }
}
