/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type SwapDataStruct = {
  swapType: BigNumberish;
  extRouter: AddressLike;
  extCalldata: BytesLike;
  needScale: boolean;
};

export type SwapDataStructOutput = [
  swapType: bigint,
  extRouter: string,
  extCalldata: string,
  needScale: boolean
] & {
  swapType: bigint;
  extRouter: string;
  extCalldata: string;
  needScale: boolean;
};

export type TokenOutputStruct = {
  tokenOut: AddressLike;
  minTokenOut: BigNumberish;
  tokenRedeemSy: AddressLike;
  bulk: AddressLike;
  euphratesSwap: AddressLike;
  swapData: SwapDataStruct;
};

export type TokenOutputStructOutput = [
  tokenOut: string,
  minTokenOut: bigint,
  tokenRedeemSy: string,
  bulk: string,
  euphratesSwap: string,
  swapData: SwapDataStructOutput
] & {
  tokenOut: string;
  minTokenOut: bigint;
  tokenRedeemSy: string;
  bulk: string;
  euphratesSwap: string;
  swapData: SwapDataStructOutput;
};

export type ApproxParamsStruct = {
  guessMin: BigNumberish;
  guessMax: BigNumberish;
  guessOffchain: BigNumberish;
  maxIteration: BigNumberish;
  eps: BigNumberish;
};

export type ApproxParamsStructOutput = [
  guessMin: bigint,
  guessMax: bigint,
  guessOffchain: bigint,
  maxIteration: bigint,
  eps: bigint
] & {
  guessMin: bigint;
  guessMax: bigint;
  guessOffchain: bigint;
  maxIteration: bigint;
  eps: bigint;
};

export type TokenInputStruct = {
  tokenIn: AddressLike;
  netTokenIn: BigNumberish;
  tokenMintSy: AddressLike;
  bulk: AddressLike;
  euphratesSwap: AddressLike;
  swapData: SwapDataStruct;
};

export type TokenInputStructOutput = [
  tokenIn: string,
  netTokenIn: bigint,
  tokenMintSy: string,
  bulk: string,
  euphratesSwap: string,
  swapData: SwapDataStructOutput
] & {
  tokenIn: string;
  netTokenIn: bigint;
  tokenMintSy: string;
  bulk: string;
  euphratesSwap: string;
  swapData: SwapDataStructOutput;
};

export interface IPActionSwapPTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "swapExactPtForSy"
      | "swapExactPtForToken"
      | "swapExactSyForPt"
      | "swapExactTokenForPt"
      | "swapPtForExactSy"
      | "swapSyForExactPt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "SwapPtAndSy" | "SwapPtAndToken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "swapExactPtForSy",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactPtForToken",
    values: [AddressLike, AddressLike, BigNumberish, TokenOutputStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactSyForPt",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      ApproxParamsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokenForPt",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      ApproxParamsStruct,
      TokenInputStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapPtForExactSy",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      ApproxParamsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapSyForExactPt",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "swapExactPtForSy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactPtForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactSyForPt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokenForPt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapPtForExactSy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapSyForExactPt",
    data: BytesLike
  ): Result;
}

export namespace SwapPtAndSyEvent {
  export type InputTuple = [
    caller: AddressLike,
    market: AddressLike,
    receiver: AddressLike,
    netPtToAccount: BigNumberish,
    netSyToAccount: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    market: string,
    receiver: string,
    netPtToAccount: bigint,
    netSyToAccount: bigint
  ];
  export interface OutputObject {
    caller: string;
    market: string;
    receiver: string;
    netPtToAccount: bigint;
    netSyToAccount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapPtAndTokenEvent {
  export type InputTuple = [
    caller: AddressLike,
    market: AddressLike,
    token: AddressLike,
    receiver: AddressLike,
    netPtToAccount: BigNumberish,
    netTokenToAccount: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    market: string,
    token: string,
    receiver: string,
    netPtToAccount: bigint,
    netTokenToAccount: bigint
  ];
  export interface OutputObject {
    caller: string;
    market: string;
    token: string;
    receiver: string;
    netPtToAccount: bigint;
    netTokenToAccount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPActionSwapPT extends BaseContract {
  connect(runner?: ContractRunner | null): IPActionSwapPT;
  waitForDeployment(): Promise<this>;

  interface: IPActionSwapPTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  swapExactPtForSy: TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactPtIn: BigNumberish,
      minSyOut: BigNumberish
    ],
    [[bigint, bigint] & { netSyOut: bigint; netSyFee: bigint }],
    "nonpayable"
  >;

  swapExactPtForToken: TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactPtIn: BigNumberish,
      output: TokenOutputStruct
    ],
    [[bigint, bigint] & { netTokenOut: bigint; netSyFee: bigint }],
    "nonpayable"
  >;

  swapExactSyForPt: TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactSyIn: BigNumberish,
      minPtOut: BigNumberish,
      guessPtOut: ApproxParamsStruct
    ],
    [[bigint, bigint] & { netPtOut: bigint; netSyFee: bigint }],
    "nonpayable"
  >;

  swapExactTokenForPt: TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      minPtOut: BigNumberish,
      guessPtOut: ApproxParamsStruct,
      input: TokenInputStruct
    ],
    [[bigint, bigint] & { netPtOut: bigint; netSyFee: bigint }],
    "payable"
  >;

  swapPtForExactSy: TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactSyOut: BigNumberish,
      maxPtIn: BigNumberish,
      guessPtIn: ApproxParamsStruct
    ],
    [[bigint, bigint] & { netPtIn: bigint; netSyFee: bigint }],
    "nonpayable"
  >;

  swapSyForExactPt: TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactPtOut: BigNumberish,
      maxSyIn: BigNumberish
    ],
    [[bigint, bigint] & { netSyIn: bigint; netSyFee: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "swapExactPtForSy"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactPtIn: BigNumberish,
      minSyOut: BigNumberish
    ],
    [[bigint, bigint] & { netSyOut: bigint; netSyFee: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapExactPtForToken"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactPtIn: BigNumberish,
      output: TokenOutputStruct
    ],
    [[bigint, bigint] & { netTokenOut: bigint; netSyFee: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapExactSyForPt"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactSyIn: BigNumberish,
      minPtOut: BigNumberish,
      guessPtOut: ApproxParamsStruct
    ],
    [[bigint, bigint] & { netPtOut: bigint; netSyFee: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapExactTokenForPt"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      minPtOut: BigNumberish,
      guessPtOut: ApproxParamsStruct,
      input: TokenInputStruct
    ],
    [[bigint, bigint] & { netPtOut: bigint; netSyFee: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapPtForExactSy"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactSyOut: BigNumberish,
      maxPtIn: BigNumberish,
      guessPtIn: ApproxParamsStruct
    ],
    [[bigint, bigint] & { netPtIn: bigint; netSyFee: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapSyForExactPt"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      market: AddressLike,
      exactPtOut: BigNumberish,
      maxSyIn: BigNumberish
    ],
    [[bigint, bigint] & { netSyIn: bigint; netSyFee: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "SwapPtAndSy"
  ): TypedContractEvent<
    SwapPtAndSyEvent.InputTuple,
    SwapPtAndSyEvent.OutputTuple,
    SwapPtAndSyEvent.OutputObject
  >;
  getEvent(
    key: "SwapPtAndToken"
  ): TypedContractEvent<
    SwapPtAndTokenEvent.InputTuple,
    SwapPtAndTokenEvent.OutputTuple,
    SwapPtAndTokenEvent.OutputObject
  >;

  filters: {
    "SwapPtAndSy(address,address,address,int256,int256)": TypedContractEvent<
      SwapPtAndSyEvent.InputTuple,
      SwapPtAndSyEvent.OutputTuple,
      SwapPtAndSyEvent.OutputObject
    >;
    SwapPtAndSy: TypedContractEvent<
      SwapPtAndSyEvent.InputTuple,
      SwapPtAndSyEvent.OutputTuple,
      SwapPtAndSyEvent.OutputObject
    >;

    "SwapPtAndToken(address,address,address,address,int256,int256)": TypedContractEvent<
      SwapPtAndTokenEvent.InputTuple,
      SwapPtAndTokenEvent.OutputTuple,
      SwapPtAndTokenEvent.OutputObject
    >;
    SwapPtAndToken: TypedContractEvent<
      SwapPtAndTokenEvent.InputTuple,
      SwapPtAndTokenEvent.OutputTuple,
      SwapPtAndTokenEvent.OutputObject
    >;
  };
}
