/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EuphratesGaugeV2 } from "./EuphratesGaugeV2";
export type { EuphratesMarketFactoryV2 } from "./EuphratesMarketFactoryV2";
export type { EuphratesMarketV2 } from "./EuphratesMarketV2";
