/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EuphratesMsgReceiveEndpointUpg } from "./EuphratesMsgReceiveEndpointUpg";
export type { EuphratesMsgReceiverAppUpg } from "./EuphratesMsgReceiverAppUpg";
export type { EuphratesMsgSendEndpointUpg } from "./EuphratesMsgSendEndpointUpg";
export type { EuphratesMsgSenderAppUpg } from "./EuphratesMsgSenderAppUpg";
