/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IAggregationExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "callBytes"
      | "finalTransactionProcessing"
      | "swapSingleSequence"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "callBytes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalTransactionProcessing",
    values: [AddressLike, AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapSingleSequence",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "callBytes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalTransactionProcessing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapSingleSequence",
    data: BytesLike
  ): Result;
}

export interface IAggregationExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): IAggregationExecutor;
  waitForDeployment(): Promise<this>;

  interface: IAggregationExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callBytes: TypedContractMethod<[data: BytesLike], [void], "payable">;

  finalTransactionProcessing: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      to: AddressLike,
      destTokenFeeData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  swapSingleSequence: TypedContractMethod<
    [data: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callBytes"
  ): TypedContractMethod<[data: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "finalTransactionProcessing"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      to: AddressLike,
      destTokenFeeData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapSingleSequence"
  ): TypedContractMethod<[data: BytesLike], [void], "nonpayable">;

  filters: {};
}
