/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RewardManager,
  RewardManagerInterface,
} from "../../../../contracts/core/RewardManager/RewardManager";

const _abi = [
  {
    inputs: [],
    name: "lastRewardBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "rewardState",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "lastBalance",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "userReward",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "accrued",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class RewardManager__factory {
  static readonly abi = _abi;
  static createInterface(): RewardManagerInterface {
    return new Interface(_abi) as RewardManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RewardManager {
    return new Contract(address, _abi, runner) as unknown as RewardManager;
  }
}
