/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RewardManagerAbstract,
  RewardManagerAbstractInterface,
} from "../../../../contracts/core/RewardManager/RewardManagerAbstract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "userReward",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "accrued",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class RewardManagerAbstract__factory {
  static readonly abi = _abi;
  static createInterface(): RewardManagerAbstractInterface {
    return new Interface(_abi) as RewardManagerAbstractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RewardManagerAbstract {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as RewardManagerAbstract;
  }
}
