/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPBulkSellerCallback,
  IPBulkSellerCallbackInterface,
} from "../../../../contracts/interfaces/IPBulkSellerSYCallback.sol/IPBulkSellerCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "ptToAccount",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "syToAccount",
        type: "int256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "swapCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPBulkSellerCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPBulkSellerCallbackInterface {
    return new Interface(_abi) as IPBulkSellerCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPBulkSellerCallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPBulkSellerCallback;
  }
}
