/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  LegacyNFTHelper,
  LegacyNFTHelperInterface,
} from "../../../../contracts/offchain-helpers/LegacyNFTHelper.sol/LegacyNFTHelper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getNumOwned",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102cc806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063402f51fa14610030575b600080fd5b61004361003e3660046101bf565b610055565b60405190815260200160405180910390f35b600080739b1bfa5d13375e8e21fdcb0a5f965974f9dcfdd173ffffffffffffffffffffffffffffffffffffffff1663bc479c3a6040518163ffffffff1660e01b8152600401602060405180830381865afa1580156100b7573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100db91906101fc565b90506000805b828110156101b7576040517fc5b8f77200000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff8616600482015260248101829052739b1bfa5d13375e8e21fdcb0a5f965974f9dcfdd19063c5b8f77290604401602060405180830381865afa15801561016e573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101929190610215565b156101a557816101a181610237565b9250505b806101af81610237565b9150506100e1565b509392505050565b6000602082840312156101d157600080fd5b813573ffffffffffffffffffffffffffffffffffffffff811681146101f557600080fd5b9392505050565b60006020828403121561020e57600080fd5b5051919050565b60006020828403121561022757600080fd5b815180151581146101f557600080fd5b60007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff820361028f577f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b506001019056fea2646970667358221220e1730db9a00131c3a7bb86eb2a042b30908422ceba562c199a47a5b2f1a4d0de64736f6c63430008110033";

type LegacyNFTHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LegacyNFTHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LegacyNFTHelper__factory extends ContractFactory {
  constructor(...args: LegacyNFTHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LegacyNFTHelper & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LegacyNFTHelper__factory {
    return super.connect(runner) as LegacyNFTHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LegacyNFTHelperInterface {
    return new Interface(_abi) as LegacyNFTHelperInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): LegacyNFTHelper {
    return new Contract(address, _abi, runner) as unknown as LegacyNFTHelper;
  }
}
