/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPActionMintRedeemStatic,
  IPActionMintRedeemStaticInterface,
} from "../../../contracts/interfaces/IPActionMintRedeemStatic";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "SY",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "bulk",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "netSyOut",
        type: "uint256",
      },
    ],
    name: "getAmountTokenToMintSy",
    outputs: [
      {
        internalType: "uint256",
        name: "netTokenIn",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "SY",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "netTokenIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "netSyIn",
        type: "uint256",
      },
    ],
    name: "getBulkSellerInfo",
    outputs: [
      {
        internalType: "address",
        name: "bulk",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalSy",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "YT",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "netSyToMint",
        type: "uint256",
      },
    ],
    name: "mintPyFromSyStatic",
    outputs: [
      {
        internalType: "uint256",
        name: "netPYOut",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "YT",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "netTokenIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "bulk",
        type: "address",
      },
    ],
    name: "mintPyFromTokenStatic",
    outputs: [
      {
        internalType: "uint256",
        name: "netPyOut",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "SY",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "netTokenIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "bulk",
        type: "address",
      },
    ],
    name: "mintSyFromTokenStatic",
    outputs: [
      {
        internalType: "uint256",
        name: "netSyOut",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "market",
        type: "address",
      },
    ],
    name: "pyIndexCurrentViewMarket",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "yt",
        type: "address",
      },
    ],
    name: "pyIndexCurrentViewYt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "YT",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "netPYToRedeem",
        type: "uint256",
      },
    ],
    name: "redeemPyToSyStatic",
    outputs: [
      {
        internalType: "uint256",
        name: "netSyOut",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "YT",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "netPYToRedeem",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "address",
        name: "bulk",
        type: "address",
      },
    ],
    name: "redeemPyToTokenStatic",
    outputs: [
      {
        internalType: "uint256",
        name: "netTokenOut",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "SY",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "netSyIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "bulk",
        type: "address",
      },
    ],
    name: "redeemSyToTokenStatic",
    outputs: [
      {
        internalType: "uint256",
        name: "netTokenOut",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPActionMintRedeemStatic__factory {
  static readonly abi = _abi;
  static createInterface(): IPActionMintRedeemStaticInterface {
    return new Interface(_abi) as IPActionMintRedeemStaticInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPActionMintRedeemStatic {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPActionMintRedeemStatic;
  }
}
