/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPActionInfoStatic,
  IPActionInfoStaticInterface,
} from "../../../contracts/interfaces/IPActionInfoStatic";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "py",
        type: "address",
      },
    ],
    name: "getPY",
    outputs: [
      {
        internalType: "address",
        name: "pt",
        type: "address",
      },
      {
        internalType: "address",
        name: "yt",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getTokensInOut",
    outputs: [
      {
        internalType: "address[]",
        name: "tokensIn",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "tokensOut",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserMarketInfo",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount",
            name: "lpBalance",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount",
            name: "ptBalance",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount",
            name: "syBalance",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount[]",
            name: "unclaimedRewards",
            type: "tuple[]",
          },
        ],
        internalType: "struct IPActionInfoStatic.UserMarketInfo",
        name: "res",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "py",
        type: "address",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserPYInfo",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount",
            name: "ptBalance",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount",
            name: "ytBalance",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount",
            name: "unclaimedInterest",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount[]",
            name: "unclaimedRewards",
            type: "tuple[]",
          },
        ],
        internalType: "struct IPActionInfoStatic.UserPYInfo",
        name: "res",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sy",
        type: "address",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserSYInfo",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount",
            name: "syBalance",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct IPActionInfoStatic.TokenAmount[]",
            name: "unclaimedRewards",
            type: "tuple[]",
          },
        ],
        internalType: "struct IPActionInfoStatic.UserSYInfo",
        name: "res",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPActionInfoStatic__factory {
  static readonly abi = _abi;
  static createInterface(): IPActionInfoStaticInterface {
    return new Interface(_abi) as IPActionInfoStaticInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPActionInfoStatic {
    return new Contract(address, _abi, runner) as unknown as IPActionInfoStatic;
  }
}
