/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPInterestManagerYTV3,
  IPInterestManagerYTV3Interface,
} from "../../../contracts/interfaces/IPInterestManagerYTV3";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "userInterest",
    outputs: [
      {
        internalType: "uint128",
        name: "lastInterestIndex",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "accruedInterest",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "lastPYIndex",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPInterestManagerYTV3__factory {
  static readonly abi = _abi;
  static createInterface(): IPInterestManagerYTV3Interface {
    return new Interface(_abi) as IPInterestManagerYTV3Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPInterestManagerYTV3 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPInterestManagerYTV3;
  }
}
