/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPMarketSwapCallback,
  IPMarketSwapCallbackInterface,
} from "../../../contracts/interfaces/IPMarketSwapCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "ptToAccount",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "syToAccount",
        type: "int256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "swapCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPMarketSwapCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPMarketSwapCallbackInterface {
    return new Interface(_abi) as IPMarketSwapCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPMarketSwapCallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPMarketSwapCallback;
  }
}
