/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPOracleForSy,
  IPOracleForSyInterface,
} from "../../../contracts/interfaces/IPOracleForSy";

const _abi = [
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPOracleForSy__factory {
  static readonly abi = _abi;
  static createInterface(): IPOracleForSyInterface {
    return new Interface(_abi) as IPOracleForSyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPOracleForSy {
    return new Contract(address, _abi, runner) as unknown as IPOracleForSy;
  }
}
