/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BoringOwnableUpgradeable } from "./BoringOwnableUpgradeable";
export type { BoringOwnableUpgradeableData } from "./BoringOwnableUpgradeableData";
