/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPSwapAggregator,
  IPSwapAggregatorInterface,
} from "../../../../contracts/router/swap-aggregator/IPSwapAggregator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "enum SwapType",
            name: "swapType",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "extRouter",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "extCalldata",
            type: "bytes",
          },
          {
            internalType: "bool",
            name: "needScale",
            type: "bool",
          },
        ],
        internalType: "struct SwapData",
        name: "swapData",
        type: "tuple",
      },
    ],
    name: "swap",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IPSwapAggregator__factory {
  static readonly abi = _abi;
  static createInterface(): IPSwapAggregatorInterface {
    return new Interface(_abi) as IPSwapAggregatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPSwapAggregator {
    return new Contract(address, _abi, runner) as unknown as IPSwapAggregator;
  }
}
